### PR TITLE
Fix include scope and directory issues

### PR DESCRIPTION
**Pull request by ralphlange**
This PR fixes the include file location and scope issues of issue #2 as discussed there.

I only updated the Makefile - the other build systems (ant, CMake, IDEs) might as well need updates. (I am allowing pushes to this PR to make that easier.)

### CODE REVIEW

**Comment by NickeZ** [comment]
Hi Ralph, thanks for the PR!

Could you rebase your commit on master to trigger Travis?

**Comment by ralphlange** [comment]
OK, sure, will do.

So now that you made 'master' public, what's the future of 'public'?
Note also that still none of the public branches have the release tag, and 'public' has the wrong non-public license.  (#1)

**Comment by NickeZ** [comment]
My plan is to remove the public branch and use the master branch as the main branch for development.

**Comment by ralphlange** [comment]
Excellent! Any step towards a more standard and more transparent workflow is highly welcome.

**Comment by NickeZ** [comment]
This was merged as a51231295f86a5c11b895d7a62b5e0b061179e91. I had to rebase and fix the tests as well. I hope this is OK.

**Pull request closed without merging**
